guesser/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('punchline/', include('punchline.urls')),
    path('', RedirectView.as_view(url='punchline/', permanent=True)),
    path('register/', user_views.register, name='register'),
    path('profile/<str:username>/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('leaderboard/', user_views.leaderboard, name='leaderboard'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

punchline/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.index, name='index'),
	path('post/<int:pk>/', views.PostDetailView.as_view(), name='post-detail'),
	path('post/<int:pk>/guess/', views.guess, name='guess'),
	path('post/create/', views.PostCreate.as_view(), name='create_post'),
	path('post/<int:pk>/update/', views.PostUpdate.as_view(), name='update_post'),
	path('post/<int:pk>/delete/', views.PostDelete.as_view(), name='delete_post'),
]

users/urls.py
from django.urls import path
from . import views

urlpatterns = []

punchline/models.py
from django.db import models
from django.urls import reverse
from django.template.defaultfilters import truncatechars
from django.contrib.auth.models import User

# Create your models here.

class Post(models.Model):
	title = models.CharField(max_length=100)
	setup = models.TextField()
	punchline = models.CharField(max_length=100)
	score = models.IntegerField(default=0)
	author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
	date_posted = models.DateTimeField(auto_now_add=True)
	
	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('post-detail', args=[str(self.id)])

	@property
	def short_title(self):
		return truncatechars(self.title, 30)
	
	@property
	def short_punchline(self):
		return truncatechars(self.punchline, 30)

class Response(models.Model):
	post = models.ForeignKey('Post', on_delete=models.SET_NULL, null=True)
	content = models.CharField(max_length=100)
	score = models.IntegerField(default=0)
	author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
	date_posted = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.content

	@property
	def short_content(self):
		return truncatechars(self.content, 30)

	class Meta:
		ordering = ['-date_posted']

import csv

def load_data():
	author = User.objects.get(username='kevin')
	with open('jokes.csv', 'r') as f:
		reader = csv.reader(f)

		i = 0
		for line in reader:
			if i > 100:
				break
			setup = line[1]
			punchline = line[2]
			if len(punchline) < 100:
				Post.objects.create(title=setup[0:100], setup=setup, punchline=punchline, author=author)
			i += 1

punchline/forms.py
from django import forms
from django.forms import ModelForm
from django.core.exceptions import ValidationError

from punchline.models import Post

class GuessPunchlineForm(forms.Form):
	punchline = forms.CharField(max_length=100)

	def clean_punchline(self):
		data = self.cleaned_data['punchline']
		return data

punchline/views.py
import random

from django.shortcuts import render, redirect, get_object_or_404

from django.views import generic
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.contrib import messages

from django.contrib.auth.models import User

from punchline.models import Post, Response
from punchline.forms import GuessPunchlineForm

from django.views.generic.edit import CreateView, UpdateView, DeleteView

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from similarity.similar import similar
# Create your views here.

def index(request):
	post_list = [post.id for post in Post.objects.all()]
	if request.user.is_authenticated:
		attempted = [post.id for post in request.user.profile.attempted.all()]
	else:
		attempted = request.session.get('attempt_id', [])
	unattempted_list = []
	for post_id in post_list:
		if post_id not in attempted:
			unattempted_list.append(post_id)

	if unattempted_list:
		return HttpResponseRedirect(reverse('guess', args=[random.choice(unattempted_list)]))
	else:
		messages.warning(request, 'You have guessed the punchline for every post! Time to create your own!')
		return HttpResponseRedirect(reverse('create_post'))

def guess(request, pk):
	post_to_guess = get_object_or_404(Post, pk=pk)

	if request.user.is_authenticated:
		correct = [post.id for post in request.user.profile.correct.all()]
		attempted = [post.id for post in request.user.profile.attempted.all()]
	else:
		correct = request.session.get('correct_id', [])
		attempted = request.session.get('attempt_id', [])

	answered_already = False
	for post_id in attempted:
		if post_id == pk:
			answered_already = True

	if post_to_guess.author == request.user:
		answered_already = True

	if request.method == 'POST':
		form = GuessPunchlineForm(request.POST)
		if form.is_valid():
			attempted.append(pk)
			if request.user.is_authenticated:
				request.user.profile.attempted.add(post_to_guess)
			else:
				request.session['attempt_id'] = attempted
			if similar(form.cleaned_data['punchline'], post_to_guess.punchline, 70):
				correct.append(pk)
				if request.user.is_authenticated:
					request.user.profile.correct.add(post_to_guess)
				else:
					request.session['correct_id'] = correct
				messages.success(request, 'Correct')
			else:
				messages.error(request, 'Incorrect')
			if request.user.is_authenticated:
				comment = Response.objects.create(post=post_to_guess, content=form.cleaned_data['punchline'], author=request.user)
			else:
				Response.objects.create(post=post_to_guess, content=form.cleaned_data['punchline'])
			return HttpResponseRedirect(reverse('post-detail', args=[pk]))
	else:
		form = GuessPunchlineForm()
	context = {
		'post_to_guess': post_to_guess,
		'form': form,
		'num_correct': len(correct),
		'num_attempts': len(attempted),
		'answered_already': answered_already
	}

	return render(request, 'guess.html', context=context)

class PostDetailView(generic.DetailView):
	model = Post

	def get_context_data(self, **kwargs):
		context = super(PostDetailView, self).get_context_data(**kwargs)
		if self.request.user.is_authenticated:
			attempted = [post.id for post in self.request.user.profile.attempted.all()]
		else:
			attempted = self.request.session.get('attempt_id', [])
		answered_already = False
		for post_id in attempted:
			if post_id == self.kwargs['pk']:
				answered_already = True
		if self.request.user == self.get_object().author:
			answered_already = True
		context['answered_already'] = answered_already
		return context

class PostCreate(LoginRequiredMixin, CreateView):
	model = Post
	fields = ['title', 'setup', 'punchline']

	def form_valid(self, form):
		form.instance.author = self.request.user
		return super(PostCreate, self).form_valid(form)

	def get_success_url(self):
		return reverse('post-detail', args=[self.object.id])

class PostUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
	model = Post
	fields = ['title', 'setup', 'punchline']

	def get_success_url(self):
		return reverse('post-detail', args=[self.object.id])

	def test_func(self):
		post = self.get_object()
		return self.request.user == post.author

class PostDelete(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
	model = Post
	success_url = reverse_lazy('index')

	def test_func(self):
		post = self.get_object()
		return self.request.user == post.author

punchline/templates/punchline/post_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<div class="media content">
	<div class="media-body">
		<p>Are you sure you want to delete the post: {{ post.title }}?</p>
		<form action="" method="POST">
		  {% csrf_token %}
		  <input type="submit" value="Yes, delete">
		</form>
	</div>
</div>
{% endblock %}

{% block scripts %}
    {% load static %}
    <script src="{% static 'js/input_formatting.js' %}"></script>
{% endblock %}

punchline/templates/punchline/post_detail.html
{% extends "base_generic.html" %}

{% block content %}
	{% if answered_already %}
		<div class="media content">
	        <div class="media-body">
	        	<h4><a href="#" class="media-heading">{{ post.title }}</a></h4>
	        	{% ifequal user post.author %}
	        		<a href="{% url 'delete_post' post.id %}" class="red-link">delete</a>
	        		<a href="{% url 'update_post' post.id %}" class="red-link">update</a>
	        	{% endifequal %}
	        	<p class="text-muted">Submitted by 
	        		{% if post.author %}
	        			<a href="{% url 'profile' post.author.username %}">{{ post.author }}</a> 
	        		{% else %}
	        			<a href="#">Anonymous</a> 
	        		{% endif %}
	        		on <a href="#">{{ post.date_posted }}</a></p>
	            <p>{{ post.setup }}</p>
	            <p>{{ post.punchline }}</p>
	        </div>
	    </div>
	    {% for response in post.response_set.all %}
	    	<div class="media content border">
	    		<div class="media-body">
					<p>
						{% if response.author %}
							<a href="{% url 'profile' response.author.username %}">{{ response.author.username }}</a>
						{% else %}
							<a href="#">Anonymous</a>
						{% endif %} 
						responded on <a href="#">{{ response.date_posted }}</a>
					</p>
					<p>{{ response }}</p>
				</div>
		    </div>
		{% endfor %}
	{% else %}
		<div class="media content">
	        <div class="media-body">
	            <p>You haven't guessed the punchline for this post yet. <a href="{% url 'guess' post.id %}">Click here</a> to try.</p>
	        </div>
	    </div>
	{% endif %}
{% endblock %}

punchline/templates/punchline/post_form.html
{% extends "base_generic.html" %}

{% block content %}
<div class="media content">
	<div class="media-body">
	  <form action="" method="post">
	    {% csrf_token %}
	    {{ form.title }}
	    {{ form.setup }}
	    {{ form.punchline }}
	    <input type="submit" value="submit">
	  </form>
	</div>
</div>
{% endblock %}

{% block scripts %}
    {% load static %}
    <script src="{% static 'js/input_formatting.js' %}"></script>
{% endblock %}